name: Manual Production Deployment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Select DEPLOY to request a protected ECR push
        required: true
        type: choice
        options: [DEPLOY]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build, Scan, and Push Image to ECR
    if: github.ref == 'refs/heads/main' && inputs.confirm == 'DEPLOY'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Local Container Image
        run: |
          docker build -t bedrock-microservice:${{ github.sha }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "bedrock-microservice:${{ github.sha }}"
          format: "table"
          exit-code: "0" # Set to 1 to break deployment on CRITICAL in strict production
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451394862:role/aws-ecs-bedrock-devsecops-deploy
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bedrock-microservice-dev
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
